# parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.5  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, FCT, [3,12]],  # 0-P1/2
   [-1, 1, DFSEBV2, [12,3,True]],  # 1-P2/4
   [-1, 1, EVE, [12,48]],
   [-1, 1, DFSEBV2, [48,3,True]],  # 3-P3/8
   [-1, 1, ME, [48,96]],
   [-1, 1, DFSEBV2, [96,3,True]],  # 5-P4/16
   [-1, 1, ME, [96,192]],
   [-1, 1, DFSEBV2, [192,3,True]],  # 7-P5/32
   [-1, 1, ME, [192,384]],
   [-1, 1, DFSEBV2, [384,3,True]],  # 9
   [-1, 1, DW, [384,3]],  
   ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [192, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   #[[-1, 7], 1, Concat, [1]],  # cat backbone P4
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [192, False]],  # 13

   [-1, 1, Conv, [96, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   #[[-1, 5], 1, Concat, [1]],  # cat backbone P3
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [96, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [96, 3, 2]],
   [[-1, 15], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [192, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [192, 3, 2]],
   [[-1, 11], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [384, False]],  # 23 (P5/32-large)

   [[18, 21, 24], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
