# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# Ghostnet backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [16, 3, 2, 1]],                    # 0-P1/2  ch_out, kernel, stride, padding, groups
   [-1, 1, GhostBottleneck, [16, 16, 3, 1]],        # 1  ch_out, ch_mid, dw-kernel, stride

   [-1, 1, GhostBottleneck, [24, 48, 3, 2]],        # 2-P2/4
   [-1, 1, GhostBottleneck, [24, 72, 3, 1]],        # 3

   [-1, 1, GhostBottleneck, [40, 72, 3, 2, True]],  # 4-P3/8
   [-1, 1, GhostBottleneck, [40, 120, 3, 1, True]], # 5

   [-1, 1, GhostBottleneck, [80, 240, 3, 2]],        # 6-P4/16
   [-1, 3, GhostBottleneck, [80, 184, 3, 1]],        # 7
   [-1, 1, GhostBottleneck, [112, 480, 3, 1, True]],
   [-1, 1, GhostBottleneck, [112, 480, 3, 1, True]],

   [-1, 1, GhostBottleneck, [160, 672, 3, 2, True]], # 10-P5/32
   [-1, 1, GhostBottleneck, [160, 960, 3, 1]],       # 11
   [-1, 1, GhostBottleneck, [160, 960, 3, 1, True]],
   [-1, 1, GhostBottleneck, [160, 960, 3, 1]],
   [-1, 1, GhostBottleneck, [160, 960, 3, 1, True]],
   [-1, 1, Conv, [960]],

   [-1, 1, SPPF, [1024, 5]], # 16
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 9], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 20

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 5], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 24 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 21], 1, Concat, [1]], # cat head P4
   [-1, 3, C3, [512, False]],  # 27 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 17], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 30 (P5/32-large)

   [[24, 27, 30], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
